### ISSUE TITLE
#9 Support User/Admin login

### ISSUE THREAD

**Issue by AfandiM** [julietrinh1/soen341#28]
As a User/Admin, I should be able to register and login.

refers to epic #9 
Story point: 9
risk: high
priority: high

Acceptance Criteria:

- The user input their user and password
- The user authentication is checked
- The user can click on the log in button
- If the log in is successful, bring the user to the homepage of the website
- Forgot password button
- Sign up page to register as a new user or admin
- If signing up, let user know if the entered email is invalid

**Comment by julietrinh1** [comment]
#29  and #30
