### ISSUE TITLE
#9: Create the option to add products as an admin

### ISSUE THREAD

**Issue by julietrinh1** [julietrinh1/soen341#6]
As an admin user, I want to be able to add products.

#9

Story points: 4
Risk: Medium
priority: Medium

Acceptance Criteria:

- If product is not already in the system, add it
- Be able to adjust all specifications of the item, such as price, image, etc
- Once the product is successfully added, it should appear in the products page, in its appropriate category, with all its specifications listed correctly

**Comment by kalsij** [comment]
closed with merge #72
